version: '3.8'

services: 
  postgre-db:
    image: postgres:13
    container_name: postgre-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetworks

  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    environment:
      - DB_NAME=postgres
      - DB_USER=postrgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres-db
      - DB_PORT=5432
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres-data: